---
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: dependabot
      include: scope
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: dependabot
      include: scope
