---
version: 2.1
orbs:
  node: circleci/node@6
jobs:
  build:
    executor: &node
      name: node/default
      tag: "22.12"
    steps:
      - checkout: {}
      - node/install-packages: {}
      - run:
          environment:
            NODE_ENV: production
          command: npm run build
      - run:
          name: PostCSS
          environment:
            NODE_ENV: production
          command: npm run postcss
      - persist_to_workspace:
          root: .
          paths:
            - dist
  deploy:
    docker:
      - image: cimg/deploy:2024.11
    steps:
      - checkout: {}
      - add_ssh_keys: {}
      - run: |
          cat \<< EOF > ~/.ssh/known_hosts
          [s9.rs2plus.gehirn.ne.jp]:22341,[153.127.109.65]:22341 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBGh08oN+BTakK+pFUgZPI9lj1mb8vSuNtl7RmTf/KUmoNYeI/y54HvNMHaWNuy4/Zco3zFctBkZIk4FxPFrVDR4=
          EOF
      - attach_workspace:
          at: .
      - run: |
          REVISION="$(git rev-parse --short HEAD)"
          ln -s ./dist "./${REVISION}"
          tar czvhf "./${REVISION}.tar.gz" "./${REVISION}"
          scp -P 22341 "${REVISION}.tar.gz" "rs2p@s9.rs2plus.gehirn.ne.jp:/var/www/yosida95.com"
          ssh -p 22341 rs2p@s9.rs2plus.gehirn.ne.jp "cd /var/www/yosida95.com; tar xzf ${REVISION}.tar.gz && ln -sfT /var/www/yosida95.com/${REVISION} ./html"
workflows:
  version: 2
  deploy:
    jobs:
      - build: {}
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
