---
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout

      - restore_cache:
          key: build-{{ checksum ".circleci/config.yml" }}
      - run: |
          if [ ! -d ".venv" ]; then
            python -m venv ./.venv
          fi
          . ./.venv/bin/activate
          pip install --upgrade pip
          pip install --upgrade 'pelican>=3.7,<4.0' 'pelican-alias>=1.1,<2.0'
      - save_cache:
          key: build-{{ checksum ".circleci/config.yml" }}
          paths:
            - ".venv"

      - run: |
          . ./.venv/bin/activate
          make publish
      - persist_to_workspace:
          root: .
          paths:
            - output
  deploy:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - add_ssh_keys
      - run: |
          cat << EOF > ~/.ssh/known_hosts
          [s9.rs2plus.gehirn.ne.jp]:22341,[153.127.109.65]:22341 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBGh08oN+BTakK+pFUgZPI9lj1mb8vSuNtl7RmTf/KUmoNYeI/y54HvNMHaWNuy4/Zco3zFctBkZIk4FxPFrVDR4=
          EOF

      - attach_workspace:
          at: .
      - run: |
          REVISION="$(git rev-parse --short HEAD)"
          ln -s ./output "./${REVISION}"
          tar czvfh "./${REVISION}.tar.gz" "./${REVISION}"
          scp -P 22341 "${REVISION}.tar.gz" "rs2p@s9.rs2plus.gehirn.ne.jp:/var/www/yosida95.com"
          ssh -p 22341 rs2p@s9.rs2plus.gehirn.ne.jp "cd /var/www/yosida95.com; tar xzf ${REVISION}.tar.gz && ln -sfT /var/www/yosida95.com/${REVISION} ./html"
workflows:
  version: 2
  deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
...
