---
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout

      - restore_cache:
          key: build-{{ checksum ".circleci/config.yml" }}
      - run: |
          if [ ! -d ".venv" ]; then
            python -m venv ./.venv
            . ./.venv/bin/activate
            pip install --upgrade pip
            pip install 'pelican>=3.7,<4.0' 'pelican-alias>=1.1,<2.0'
          fi
      - save_cache:
          key: build-{{ checksum ".circleci/config.yml" }}
          paths:
            - ".venv"

      - run: |
          . ./.venv/bin/activate
          make publish
      - persist_to_workspace:
          root: .
          paths:
            - output
  deploy:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: |
          REVISION="$(git rev-parse --short HEAD)"
          scp -P 22329 -r ./output/ "rs2p@s1.rs2p.gis.gehirn.jp:/var/www/yosida95.com/${REVISION}"
          ssh -p 22329 rs2p@s1.rs2p.gis.gehirn.jp "ln -sfT /var/www/yosida95.com/${REVISION} /var/www/yosida95.com/html"
workflows:
  version: 2
  deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
...
