---
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout

      - restore_cache:
          key: build-{{ checksum ".circleci/config.yml" }}
      - run: |
          if [ ! -d ".venv" ]; then
            python -m venv ./.venv
          fi
          . ./.venv/bin/activate
          pip install --upgrade pip
          pip install --upgrade 'pelican>=3.7,<4.0' 'pelican-alias>=1.1,<2.0'
      - save_cache:
          key: build-{{ checksum ".circleci/config.yml" }}
          paths:
            - ".venv"

      - run: |
          . ./.venv/bin/activate
          make publish
      - persist_to_workspace:
          root: .
          paths:
            - output
  deploy:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - add_ssh_keys
      - run: |
          cat << EOF > ~/.ssh/known_hosts
          [s1.rs2p.gis.gehirn.jp]:22329,[133.242.85.169]:22329 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBPws3mCejM5wXZzASVkQcUCUmK1CZ9bylhrjvgds2L7NLYwyJ/LWWUjxpFbli9jI1qod7swrRII0T1tyOvsAErE=
          EOF

      - attach_workspace:
          at: .
      - run: |
          REVISION="$(git rev-parse --short HEAD)"
          ln -s ./output "./${REVISION}"
          tar czvfh "./${REVISION}.tar.gz" "./${REVISION}"
          scp -P 22329 "${REVISION}.tar.gz" "rs2p@s1.rs2p.gis.gehirn.jp:/var/www/yosida95.com"
          ssh -p 22329 rs2p@s1.rs2p.gis.gehirn.jp "cd /var/www/yosida95.com; tar xzf ${REVISION}.tar.gz && ln -sfT /var/www/yosida95.com/${REVISION} ./html"
workflows:
  version: 2
  deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
...
